config/routes.rb
DataPet::Application.routes.draw do

  match '/main', controller: :application, action: :main
  root to: 'application#main'

  resources :databases do
    collection do
      post :test
      get :list
    end

    member do
      get :details
      get :tables

      resource :tables do
        collection do
          post :query
          post :columns
          post :database_relations
          get :database_relations
        end
      end

    end
  end

  resources :database_relations do
    collection do
      get :list
    end

    member do
      post :query
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='data-pet'>

<head>
  <title>DataPet</title>

  <!-- angular-ui css -->
  <link rel="stylesheet" type='text/css' href="/stylesheets/mobile-angular-ui-base.css"/>
  <link rel="stylesheet" type="text/css" href="/stylesheets/angular-animate.css"/>
  <!-- application css -->


  <link rel="styleSheet" type="text/css" href="/stylesheets/ui-grid.css"/>

  <link rel="stylesheet" type="text/css" href="/stylesheets/loading-bar.css"/>

  <link rel='stylesheet' type='text/css' href='/stylesheets/base.css'/>

  <%= csrf_meta_tags %>
</head>

<body>
<%= yield :sidebar %>

<div class="sidebar sidebar-right ng-scope" toggleable="" parent-active-class="sidebar-right-in" id="rightSidebar">
  <div class="scrollable">
    <div class="scrollable-content">
      <div class="list-group" toggle="off" bubble="" target="rightSidebar">
        <div class="list-group-item">
          <a <%= target_blank? %> href='<%= databases_path %>' class="btn btn-navbar">Databases</a>
        </div>
        <div class="list-group-item">
          <a <%= target_blank? %> href='<%= new_database_path %>' class="btn btn-navbar">New Database</a>
        </div>
        <div class="list-group-item">
          <a <%= target_blank? %> href='<%= database_relations_path %>' class="btn btn-navbar">Relations</a>
        </div>
        <div class="list-group-item">
          <a <%= target_blank? %> href='<%= new_database_relation_path %>' class="btn btn-navbar">New Relation</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="app">
  <div class="navbar navbar-app navbar-absolute-top" id='top_navigation_bar'>
    <div class="navbar-brand navbar-brand-center">
      <span><a href="/">DataPet</a></span>
    </div>
    <div class="btn-group pull-left">
      <div ng-click="toggle('mainSidebar')" class="btn btn-navbar">
        <i class="fa fa-bars"></i> Databases
      </div>
    </div>
    <div class="btn-group pull-right">
      <div ng-click="toggle('rightSidebar')" class="btn btn-navbar">
        Menu <i class="fa fa-bars"></i>
      </div>
    </div>
  </div>
  <div class='app-body'>
    <div class="app-content">
      <%= yield %>
    </div>
  </div>
</div>

<!-- notices -->
<div ng-controller="noticesController">
  <div ng-repeat="notice in notices" ng-click="removeNotice(notice.id)" class="alert alert-custom {{notice.class}}" ng-style="{'top':'{{notice.top}}px'}">
    {{notice.text}}
  </div>
</div>

<!-- angular js -->
<script src='/javascripts/angular/angular.min.js'></script>
<script src="/javascripts/angular/mobile-angular-ui.min.js"></script>


<!-- jQuery -->
<script src='/javascripts/jquery/jquery-2.0.3.min.js'></script>
<script src='/javascripts/jquery/jquery-ui.js'></script>

<!-- Bootstrap -->
<script src='/javascripts/bootstrap/bootstrap.min.js'></script>
<script src='/javascripts/bootstrap/ui-bootstrap.min.js'></script>
<script src='/javascripts/bootstrap/ui-bootstrap-tpls.min.js'></script>
<script type="text/javascript" src="/javascripts/ui-grid.js"></script>
<script type="text/javascript" src="/javascripts/angular/directives/loading-bar.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular-animate.min.js"></script>

<script>var app = angular.module('data-pet', ['ui.bootstrap', 'mobile-angular-ui', 'angular-loading-bar', 'ngAnimate','ui.grid', 'ui.grid.edit', 'ui.grid.resizeColumns', 'ui.grid.selection', 'ui.grid.moveColumns']);</script>

<!-- noticesController used to display messages to the user -->
<script src='/javascripts/angular/controllers/notices/notices_controller.js'></script>
<script type="text/javascript" src="/javascripts/angular/services/http_services.js"></script>
<script type="text/javascript" src="/javascripts/angular/filters/with.js"></script>

<!-- Page Specific JS -->
<%= yield :javascripts %>
</body>

</html>